server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sys?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: 123456

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: ttl-producer
  consumer:
    group: my-group